/* Automatically generated by wasm2c */
#ifndef SNAKE_H_GENERATED_
#define SNAKE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_imports;

typedef struct w2c_snake {
  struct w2c_imports* w2c_imports_instance;
  u32 w2c_memoryRegionLogBytesOffset;
  u32 w2c_memoryRegionLogBytesN;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_memoryRegionCanvasBytesOffset;
  u32 w2c_memoryRegionCanvasBytesN;
  u32 w2c_g6;
  u32 w2c_g7;
  u32 w2c_g8;
  u32 w2c_g9;
  u32 w2c_g10;
  u32 w2c_g11;
  u32 w2c_g12;
  u32 w2c_g13;
  u32 w2c_g14;
  u32 w2c_g15;
  u32 w2c_g16;
  u32 w2c_g17;
  u32 w2c_g18;
  u32 w2c_g19;
  u32 w2c_g20;
  u32 w2c_g21;
  u32 w2c_g22;
  u32 w2c_g23;
  u32 w2c_g24;
  u32 w2c_g25;
  u32 w2c_g26;
  u32 w2c_g27;
  u32 w2c_g28;
  u32 w2c_g29;
  u32 w2c_g30;
  u32 w2c_g31;
  u32 w2c_g32;
  u32 w2c_g33;
  u32 w2c_g34;
  u32 w2c_g35;
  u32 w2c_g36;
  u32 w2c_g37;
  u32 w2c_g38;
  u32 w2c_g39;
  u32 w2c_g40;
  u32 w2c_g41;
  u32 w2c_g42;
  u32 w2c_g43;
  u32 w2c_g44;
  u32 w2c_g45;
  u32 w2c_g46;
  u32 w2c_g47;
  u32 w2c_g48;
  u64 w2c_g49;
  u64 w2c_g50;
  u64 w2c_g51;
  u64 w2c_g52;
  u64 w2c_g53;
  u64 w2c_g54;
  u64 w2c_g55;
  u64 w2c_g56;
  u64 w2c_g57;
  u64 w2c_g58;
  u64 w2c_g59;
  u64 w2c_g60;
  u64 w2c_g61;
  u64 w2c_g62;
  u64 w2c_g63;
  u64 w2c_g64;
  u64 w2c_g65;
  u64 w2c_g66;
  u64 w2c_g67;
  u64 w2c_g68;
  u64 w2c_g69;
  u64 w2c_g70;
  u64 w2c_g71;
  u64 w2c_g72;
  u64 w2c_g73;
  u64 w2c_g74;
  u64 w2c_g75;
  u64 w2c_g76;
  u64 w2c_g77;
  u64 w2c_g78;
  u64 w2c_g79;
  u64 w2c_g80;
  u32 w2c_g81;
  f32 w2c_g82;
  f32 w2c_g83;
  f32 w2c_g84;
  u32 w2c_g85;
  u32 w2c_g86;
  u32 w2c_g87;
  u32 w2c_g88;
  u32 w2c_g89;
  f32 w2c_g90;
  f32 w2c_g91;
  f32 w2c_g92;
  u32 w2c_g93;
  u32 w2c_g94;
  u32 w2c_g95;
  u32 w2c_g96;
  u32 w2c_g97;
  u32 w2c_g98;
  u32 w2c_g99;
  u32 w2c_g100;
  u32 w2c_g101;
  u32 w2c_g102;
  u32 w2c_g103;
  u32 w2c_g104;
  u32 w2c_g105;
  f32 w2c_g106;
  f32 w2c_g107;
  f32 w2c_g108;
  f32 w2c_g109;
  f32 w2c_g110;
  f32 w2c_g111;
  u32 w2c_g112;
  u32 w2c_g113;
  u32 w2c_g114;
  f32 w2c_g115;
  f32 w2c_g116;
  u32 w2c_g117;
  u32 w2c_g118;
  u32 w2c_g119;
  wasm_rt_memory_t w2c_memory;
} w2c_snake;

void wasm2c_snake_instantiate(w2c_snake*, struct w2c_imports*);
void wasm2c_snake_free(w2c_snake*);
wasm_rt_func_type_t wasm2c_snake_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'imports' 'logFromNBytesOfMemory' */
void w2c_imports_logFromNBytesOfMemory(struct w2c_imports*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_snake_memory(w2c_snake* instance);

/* export: 'memoryRegionLogBytesOffset' */
u32* w2c_snake_memoryRegionLogBytesOffset(w2c_snake* instance);

/* export: 'memoryRegionLogBytesN' */
u32* w2c_snake_memoryRegionLogBytesN(w2c_snake* instance);

/* export: 'memoryRegionCanvasBytesOffset' */
u32* w2c_snake_memoryRegionCanvasBytesOffset(w2c_snake* instance);

/* export: 'memoryRegionCanvasBytesN' */
u32* w2c_snake_memoryRegionCanvasBytesN(w2c_snake* instance);

/* export: 'update' */
void w2c_snake_update(w2c_snake*, f32);

/* export: 'handleKeyDown' */
void w2c_snake_handleKeyDown(w2c_snake*, u32);

/* export: 'resize' */
void w2c_snake_resize(w2c_snake*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* SNAKE_H_GENERATED_ */
