/* Automatically generated by wasm2c */
#ifndef SNAKE_H_GENERATED_
#define SNAKE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_imports;

typedef struct w2c_snake {
  struct w2c_imports* w2c_imports_instance;
  u32 w2c_memoryRegionLogBytesOffset;
  u32 w2c_memoryRegionLogBytesN;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_memoryRegionCanvasBytesOffset;
  u32 w2c_memoryRegionCanvasBytesN;
  u32 w2c_g6;
  u32 w2c_INPUT_START;
  u32 w2c_INPUT_UPDATE;
  u32 w2c_INPUT_END;
  u32 w2c_KEY_SPACE;
  u32 w2c_KEY_W;
  u32 w2c_KEY_w;
  u32 w2c_ARROW_UP;
  u32 w2c_KEY_A;
  u32 w2c_KEY_a;
  u32 w2c_ARROW_LEFT;
  u32 w2c_KEY_S;
  u32 w2c_KEY_s;
  u32 w2c_ARROW_DOWN;
  u32 w2c_KEY_D;
  u32 w2c_KEY_d;
  u32 w2c_ARROW_RIGHT;
  u32 w2c_g23;
  u32 w2c_g24;
  u32 w2c_g25;
  u32 w2c_g26;
  u32 w2c_g27;
  u32 w2c_g28;
  f32 w2c_g29;
  f32 w2c_g30;
  f32 w2c_g31;
  f32 w2c_g32;
  u32 w2c_g33;
  u32 w2c_g34;
  u32 w2c_g35;
  u32 w2c_g36;
  u32 w2c_g37;
  u32 w2c_g38;
  u32 w2c_g39;
  u32 w2c_g40;
  u32 w2c_g41;
  u32 w2c_g42;
  f32 w2c_g43;
  u32 w2c_g44;
  u32 w2c_g45;
  f32 w2c_g46;
  f32 w2c_g47;
  u32 w2c_g48;
  f32 w2c_g49;
  f32 w2c_g50;
  u32 w2c_g51;
  f32 w2c_g52;
  f32 w2c_g53;
  f32 w2c_g54;
  f32 w2c_g55;
  u32 w2c_g56;
  u32 w2c_g57;
  u32 w2c_g58;
  f32 w2c_g59;
  f32 w2c_g60;
  u32 w2c_g61;
  u32 w2c_g62;
  u32 w2c_g63;
  u32 w2c_g64;
  u32 w2c_g65;
  u32 w2c_g66;
  u32 w2c_g67;
  f32 w2c_g68;
  f32 w2c_g69;
  f32 w2c_g70;
  u32 w2c_g71;
  u32 w2c_g72;
  u32 w2c_g73;
  u32 w2c_g74;
  u32 w2c_g75;
  u32 w2c_g76;
  u32 w2c_g77;
  u32 w2c_g78;
  u32 w2c_g79;
  u32 w2c_g80;
  u32 w2c_g81;
  u32 w2c_g82;
  u32 w2c_g83;
  u32 w2c_g84;
  u32 w2c_g85;
  u32 w2c_g86;
  u32 w2c_g87;
  u32 w2c_g88;
  u32 w2c_g89;
  u32 w2c_g90;
  u32 w2c_g91;
  u32 w2c_g92;
  u32 w2c_g93;
  u32 w2c_g94;
  u32 w2c_g95;
  u32 w2c_g96;
  u32 w2c_g97;
  u32 w2c_g98;
  u32 w2c_g99;
  u32 w2c_g100;
  u32 w2c_g101;
  u32 w2c_g102;
  u32 w2c_g103;
  u32 w2c_g104;
  u32 w2c_g105;
  u32 w2c_g106;
  u32 w2c_g107;
  u32 w2c_g108;
  u32 w2c_g109;
  u32 w2c_g110;
  u32 w2c_g111;
  u32 w2c_g112;
  u32 w2c_g113;
  u64 w2c_g114;
  u64 w2c_g115;
  u64 w2c_g116;
  u64 w2c_g117;
  u64 w2c_g118;
  u64 w2c_g119;
  u64 w2c_g120;
  u64 w2c_g121;
  u64 w2c_g122;
  u64 w2c_g123;
  u64 w2c_g124;
  u64 w2c_g125;
  u64 w2c_g126;
  u64 w2c_g127;
  u64 w2c_g128;
  u64 w2c_g129;
  u64 w2c_g130;
  u64 w2c_g131;
  u64 w2c_g132;
  u64 w2c_g133;
  u64 w2c_g134;
  u64 w2c_g135;
  u64 w2c_g136;
  u64 w2c_g137;
  u64 w2c_g138;
  u64 w2c_g139;
  u64 w2c_g140;
  u64 w2c_g141;
  u64 w2c_g142;
  u64 w2c_g143;
  u64 w2c_g144;
  u64 w2c_g145;
  u32 w2c_g146;
  wasm_rt_memory_t w2c_memory;
} w2c_snake;

void wasm2c_snake_instantiate(w2c_snake*, struct w2c_imports*);
void wasm2c_snake_free(w2c_snake*);
wasm_rt_func_type_t wasm2c_snake_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'imports' 'logFromNBytesOfMemory' */
void w2c_imports_logFromNBytesOfMemory(struct w2c_imports*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_snake_memory(w2c_snake* instance);

/* export: 'memoryRegionLogBytesOffset' */
u32* w2c_snake_memoryRegionLogBytesOffset(w2c_snake* instance);

/* export: 'memoryRegionLogBytesN' */
u32* w2c_snake_memoryRegionLogBytesN(w2c_snake* instance);

/* export: 'memoryRegionCanvasBytesOffset' */
u32* w2c_snake_memoryRegionCanvasBytesOffset(w2c_snake* instance);

/* export: 'memoryRegionCanvasBytesN' */
u32* w2c_snake_memoryRegionCanvasBytesN(w2c_snake* instance);

/* export: 'INPUT_START' */
u32* w2c_snake_INPUT_START(w2c_snake* instance);

/* export: 'INPUT_UPDATE' */
u32* w2c_snake_INPUT_UPDATE(w2c_snake* instance);

/* export: 'INPUT_END' */
u32* w2c_snake_INPUT_END(w2c_snake* instance);

/* export: 'KEY_SPACE' */
u32* w2c_snake_KEY_SPACE(w2c_snake* instance);

/* export: 'KEY_W' */
u32* w2c_snake_KEY_W(w2c_snake* instance);

/* export: 'KEY_w' */
u32* w2c_snake_KEY_w(w2c_snake* instance);

/* export: 'ARROW_UP' */
u32* w2c_snake_ARROW_UP(w2c_snake* instance);

/* export: 'KEY_A' */
u32* w2c_snake_KEY_A(w2c_snake* instance);

/* export: 'KEY_a' */
u32* w2c_snake_KEY_a(w2c_snake* instance);

/* export: 'ARROW_LEFT' */
u32* w2c_snake_ARROW_LEFT(w2c_snake* instance);

/* export: 'KEY_S' */
u32* w2c_snake_KEY_S(w2c_snake* instance);

/* export: 'KEY_s' */
u32* w2c_snake_KEY_s(w2c_snake* instance);

/* export: 'ARROW_DOWN' */
u32* w2c_snake_ARROW_DOWN(w2c_snake* instance);

/* export: 'KEY_D' */
u32* w2c_snake_KEY_D(w2c_snake* instance);

/* export: 'KEY_d' */
u32* w2c_snake_KEY_d(w2c_snake* instance);

/* export: 'ARROW_RIGHT' */
u32* w2c_snake_ARROW_RIGHT(w2c_snake* instance);

/* export: 'update' */
void w2c_snake_update(w2c_snake*, f32);

/* export: 'input_key' */
void w2c_snake_input_key(w2c_snake*, u32, u32);

/* export: 'input_touch' */
void w2c_snake_input_touch(w2c_snake*, u32, f32, f32);

/* export: 'resize' */
void w2c_snake_resize(w2c_snake*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* SNAKE_H_GENERATED_ */
