/* Automatically generated by wasm2c */
#include <assert.h>
#include <math.h>
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#if defined(__MINGW32__)
#include <malloc.h>
#elif defined(_MSC_VER)
#include <intrin.h>
#include <malloc.h>
#define alloca _alloca
#elif defined(__FreeBSD__) || defined(__OpenBSD__)
#include <stdlib.h>
#else
#include <alloca.h>
#endif

#include "snake.h"

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_USE_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#define UNREACHABLE TRAP(UNREACHABLE)

static inline bool func_types_eq(const wasm_rt_func_type_t a,
                                 const wasm_rt_func_type_t b) {
  return (a == b) || LIKELY(a && b && !memcmp(a, b, 32));
}

#define CHECK_CALL_INDIRECT(table, ft, x)                \
  (LIKELY((x) < table.size && table.data[x].func &&      \
          func_types_eq(ft, table.data[x].func_type)) || \
   TRAP(CALL_INDIRECT))

#define DO_CALL_INDIRECT(table, t, x, ...) ((t)table.data[x].func)(__VA_ARGS__)

#define CALL_INDIRECT(table, t, ft, x, ...) \
  (CHECK_CALL_INDIRECT(table, ft, x),       \
   DO_CALL_INDIRECT(table, t, x, __VA_ARGS__))

#ifdef SUPPORT_MEMORY64
#define RANGE_CHECK(mem, offset, len)              \
  do {                                             \
    uint64_t res;                                  \
    if (__builtin_add_overflow(offset, len, &res)) \
      TRAP(OOB);                                   \
    if (UNLIKELY(res > mem->size))                 \
      TRAP(OOB);                                   \
  } while (0);
#else
#define RANGE_CHECK(mem, offset, len)               \
  if (UNLIKELY(offset + (uint64_t)len > mem->size)) \
    TRAP(OOB);
#endif

#if WASM_RT_MEMCHECK_GUARD_PAGES
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t) RANGE_CHECK(mem, a, sizeof(t))
#endif

#ifdef __GNUC__
#define FORCE_READ_INT(var) __asm__("" ::"r"(var));
// Clang on Mips requires "f" constraints on floats
// See https://github.com/llvm/llvm-project/issues/64241
#if defined(__clang__) && \
    (defined(mips) || defined(__mips__) || defined(__mips))
#define FORCE_READ_FLOAT(var) __asm__("" ::"f"(var));
#else
#define FORCE_READ_FLOAT(var) __asm__("" ::"r"(var));
#endif
#else
#define FORCE_READ_INT(var)
#define FORCE_READ_FLOAT(var)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void* dest, const void* src, size_t n) {
  if (!n) {
    return;
  }
  size_t i = 0;
  u8* dest_chars = dest;
  wasm_rt_memcpy(dest, src, n);
  for (i = 0; i < (n >> 1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s)                   \
  do {                                          \
    RANGE_CHECK((&m), m.size - o - s, s);       \
    load_data(&(m.data[m.size - o - s]), i, s); \
  } while (0)
#define DEFINE_LOAD(name, t1, t2, t3, force_read)                      \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {             \
    MEMCHECK(mem, addr, t1);                                           \
    t1 result;                                                         \
    wasm_rt_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], \
                   sizeof(t1));                                        \
    force_read(result);                                                \
    return (t3)(t2)result;                                             \
  }

#define DEFINE_STORE(name, t1, t2)                                      \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {  \
    MEMCHECK(mem, addr, t1);                                            \
    t1 wrapped = (t1)value;                                             \
    wasm_rt_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, \
                   sizeof(t1));                                         \
  }
#else
static inline void load_data(void* dest, const void* src, size_t n) {
  if (!n) {
    return;
  }
  wasm_rt_memcpy(dest, src, n);
}
#define LOAD_DATA(m, o, i, s)      \
  do {                             \
    RANGE_CHECK((&m), o, s);       \
    load_data(&(m.data[o]), i, s); \
  } while (0)
#define DEFINE_LOAD(name, t1, t2, t3, force_read)          \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) { \
    MEMCHECK(mem, addr, t1);                               \
    t1 result;                                             \
    wasm_rt_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    force_read(result);                                    \
    return (t3)(t2)result;                                 \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    wasm_rt_memcpy(&mem->data[addr], &wrapped, sizeof(t1));            \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load, u64, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(f32_load, f32, f32, f32, FORCE_READ_FLOAT)
DEFINE_LOAD(f64_load, f64, f64, f64, FORCE_READ_FLOAT)
DEFINE_LOAD(i32_load8_s, s8, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_s, s8, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load8_u, u8, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_u, u8, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_s, s16, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_s, s16, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_u, u16, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_u, u16, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_s, s32, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_u, u32, u64, u64, FORCE_READ_INT)
DEFINE_STORE(i32_store, u32, u32)
DEFINE_STORE(i64_store, u64, u64)
DEFINE_STORE(f32_store, f32, f32)
DEFINE_STORE(f64_store, f64, f64)
DEFINE_STORE(i32_store8, u8, u32)
DEFINE_STORE(i32_store16, u16, u32)
DEFINE_STORE(i64_store8, u8, u64)
DEFINE_STORE(i64_store16, u16, u64)
DEFINE_STORE(i64_store32, u32, u64)

#if defined(_MSC_VER)

// Adapted from
// https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h

static inline int I64_CLZ(unsigned long long v) {
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  if (_BitScanReverse64(&r, v)) {
    return 63 - r;
  }
#else
  if (_BitScanReverse(&r, (unsigned long)(v >> 32))) {
    return 31 - r;
  } else if (_BitScanReverse(&r, (unsigned long)v)) {
    return 63 - r;
  }
#endif
  return 64;
}

static inline int I32_CLZ(unsigned long v) {
  unsigned long r = 0;
  if (_BitScanReverse(&r, v)) {
    return 31 - r;
  }
  return 32;
}

static inline int I64_CTZ(unsigned long long v) {
  if (!v) {
    return 64;
  }
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  _BitScanForward64(&r, v);
  return (int)r;
#else
  if (_BitScanForward(&r, (unsigned int)(v))) {
    return (int)(r);
  }

  _BitScanForward(&r, (unsigned int)(v >> 32));
  return (int)(r + 32);
#endif
}

static inline int I32_CTZ(unsigned long v) {
  if (!v) {
    return 32;
  }
  unsigned long r = 0;
  _BitScanForward(&r, v);
  return (int)r;
}

#define POPCOUNT_DEFINE_PORTABLE(f_n, T)                            \
  static inline u32 f_n(T x) {                                      \
    x = x - ((x >> 1) & (T) ~(T)0 / 3);                             \
    x = (x & (T) ~(T)0 / 15 * 3) + ((x >> 2) & (T) ~(T)0 / 15 * 3); \
    x = (x + (x >> 4)) & (T) ~(T)0 / 255 * 15;                      \
    return (T)(x * ((T) ~(T)0 / 255)) >> (sizeof(T) - 1) * 8;       \
  }

POPCOUNT_DEFINE_PORTABLE(I32_POPCNT, u32)
POPCOUNT_DEFINE_PORTABLE(I64_POPCNT, u64)

#undef POPCOUNT_DEFINE_PORTABLE

#else

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#endif

#define DIV_S(ut, min, x, y)                                      \
  ((UNLIKELY((y) == 0))                                           \
       ? TRAP(DIV_BY_ZERO)                                        \
       : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                             : (ut)((x) / (y)))

#define REM_S(ut, min, x, y) \
  ((UNLIKELY((y) == 0))      \
       ? TRAP(DIV_BY_ZERO)   \
       : (UNLIKELY((x) == min && (y) == -1)) ? 0 : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
                                                : (x < y) ? x : y)

#define FMAX(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
                                                : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                           \
  ((UNLIKELY((x) != (x)))                                                 \
       ? TRAP(INVALID_CONVERSION)                                         \
       : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                     : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) \
  TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) \
  TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) \
  TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) \
  TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                          \
  ((UNLIKELY((x) != (x)))                                                \
       ? TRAP(INVALID_CONVERSION)                                        \
       : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                    : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296., x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))                                       \
       ? 0                                                      \
       : (UNLIKELY(!((x)minop(min))))                           \
             ? smin                                             \
             : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x)                                            \
  TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x)                                              \
  TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, \
              INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x)                                        \
  TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x)                                              \
  TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, \
              INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x)               \
  ((UNLIKELY((x) != (x))) ? 0                           \
                          : (UNLIKELY(!((x) > (ft)-1))) \
                                ? 0                     \
                                : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F64(x) \
  TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)         \
  static inline t2 name(t1 x) {                  \
    t2 result;                                   \
    wasm_rt_memcpy(&result, &x, sizeof(result)); \
    return result;                               \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)

static float quiet_nanf(float x) {
  uint32_t tmp;
  wasm_rt_memcpy(&tmp, &x, 4);
  tmp |= 0x7fc00000lu;
  wasm_rt_memcpy(&x, &tmp, 4);
  return x;
}

static double quiet_nan(double x) {
  uint64_t tmp;
  wasm_rt_memcpy(&tmp, &x, 8);
  tmp |= 0x7ff8000000000000llu;
  wasm_rt_memcpy(&x, &tmp, 8);
  return x;
}

static double wasm_quiet(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return x;
}

static float wasm_quietf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return x;
}

static double wasm_floor(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return floor(x);
}

static float wasm_floorf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return floorf(x);
}

static double wasm_ceil(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return ceil(x);
}

static float wasm_ceilf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return ceilf(x);
}

static double wasm_trunc(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return trunc(x);
}

static float wasm_truncf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return truncf(x);
}

static float wasm_nearbyintf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return nearbyintf(x);
}

static double wasm_nearbyint(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return nearbyint(x);
}

static float wasm_fabsf(float x) {
  if (UNLIKELY(isnan(x))) {
    uint32_t tmp;
    wasm_rt_memcpy(&tmp, &x, 4);
    tmp = tmp & ~(1UL << 31);
    wasm_rt_memcpy(&x, &tmp, 4);
    return x;
  }
  return fabsf(x);
}

static double wasm_fabs(double x) {
  if (UNLIKELY(isnan(x))) {
    uint64_t tmp;
    wasm_rt_memcpy(&tmp, &x, 8);
    tmp = tmp & ~(1ULL << 63);
    wasm_rt_memcpy(&x, &tmp, 8);
    return x;
  }
  return fabs(x);
}

static double wasm_sqrt(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return sqrt(x);
}

static float wasm_sqrtf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return sqrtf(x);
}

static inline void memory_fill(wasm_rt_memory_t* mem, u32 d, u32 val, u32 n) {
  RANGE_CHECK(mem, d, n);
  memset(mem->data + d, val, n);
}

static inline void memory_copy(wasm_rt_memory_t* dest,
                               const wasm_rt_memory_t* src,
                               u32 dest_addr,
                               u32 src_addr,
                               u32 n) {
  RANGE_CHECK(dest, dest_addr, n);
  RANGE_CHECK(src, src_addr, n);
  memmove(dest->data + dest_addr, src->data + src_addr, n);
}

static inline void memory_init(wasm_rt_memory_t* dest,
                               const u8* src,
                               u32 src_size,
                               u32 dest_addr,
                               u32 src_addr,
                               u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  LOAD_DATA((*dest), dest_addr, src + src_addr, n);
}

typedef struct {
  enum { RefFunc, RefNull, GlobalGet } expr_type;
  wasm_rt_func_type_t type;
  wasm_rt_function_ptr_t func;
  wasm_rt_tailcallee_t func_tailcallee;
  size_t module_offset;
} wasm_elem_segment_expr_t;

static inline void funcref_table_init(wasm_rt_funcref_table_t* dest,
                                      const wasm_elem_segment_expr_t* src,
                                      u32 src_size,
                                      u32 dest_addr,
                                      u32 src_addr,
                                      u32 n,
                                      void* module_instance) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  if (UNLIKELY(dest_addr + (uint64_t)n > dest->size))
    TRAP(OOB);
  for (u32 i = 0; i < n; i++) {
    const wasm_elem_segment_expr_t* const src_expr = &src[src_addr + i];
    wasm_rt_funcref_t* const dest_val = &(dest->data[dest_addr + i]);
    switch (src_expr->expr_type) {
      case RefFunc:
        *dest_val = (wasm_rt_funcref_t){
            src_expr->type, src_expr->func, src_expr->func_tailcallee,
            (char*)module_instance + src_expr->module_offset};
        break;
      case RefNull:
        *dest_val = wasm_rt_funcref_null_value;
        break;
      case GlobalGet:
        *dest_val = **(wasm_rt_funcref_t**)((char*)module_instance +
                                            src_expr->module_offset);
        break;
    }
  }
}

// Currently wasm2c only supports initializing externref tables with ref.null.
static inline void externref_table_init(wasm_rt_externref_table_t* dest,
                                        u32 src_size,
                                        u32 dest_addr,
                                        u32 src_addr,
                                        u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  if (UNLIKELY(dest_addr + (uint64_t)n > dest->size))
    TRAP(OOB);
  for (u32 i = 0; i < n; i++) {
    dest->data[dest_addr + i] = wasm_rt_externref_null_value;
  }
}

#define DEFINE_TABLE_COPY(type)                                              \
  static inline void type##_table_copy(wasm_rt_##type##_table_t* dest,       \
                                       const wasm_rt_##type##_table_t* src,  \
                                       u32 dest_addr, u32 src_addr, u32 n) { \
    if (UNLIKELY(dest_addr + (uint64_t)n > dest->size))                      \
      TRAP(OOB);                                                             \
    if (UNLIKELY(src_addr + (uint64_t)n > src->size))                        \
      TRAP(OOB);                                                             \
                                                                             \
    memmove(dest->data + dest_addr, src->data + src_addr,                    \
            n * sizeof(wasm_rt_##type##_t));                                 \
  }

DEFINE_TABLE_COPY(funcref)
DEFINE_TABLE_COPY(externref)

#define DEFINE_TABLE_GET(type)                        \
  static inline wasm_rt_##type##_t type##_table_get(  \
      const wasm_rt_##type##_table_t* table, u32 i) { \
    if (UNLIKELY(i >= table->size))                   \
      TRAP(OOB);                                      \
    return table->data[i];                            \
  }

DEFINE_TABLE_GET(funcref)
DEFINE_TABLE_GET(externref)

#define DEFINE_TABLE_SET(type)                                               \
  static inline void type##_table_set(const wasm_rt_##type##_table_t* table, \
                                      u32 i, const wasm_rt_##type##_t val) { \
    if (UNLIKELY(i >= table->size))                                          \
      TRAP(OOB);                                                             \
    table->data[i] = val;                                                    \
  }

DEFINE_TABLE_SET(funcref)
DEFINE_TABLE_SET(externref)

#define DEFINE_TABLE_FILL(type)                                               \
  static inline void type##_table_fill(const wasm_rt_##type##_table_t* table, \
                                       u32 d, const wasm_rt_##type##_t val,   \
                                       u32 n) {                               \
    if (UNLIKELY((uint64_t)d + n > table->size))                              \
      TRAP(OOB);                                                              \
    for (uint32_t i = d; i < d + n; i++) {                                    \
      table->data[i] = val;                                                   \
    }                                                                         \
  }

DEFINE_TABLE_FILL(funcref)
DEFINE_TABLE_FILL(externref)

#if defined(__GNUC__) || defined(__clang__)
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char* const x
#define FUNC_TYPE_EXTERN_T(x) const char* const x
#define FUNC_TYPE_T(x) static const char* const x
#else
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char x[]
#define FUNC_TYPE_EXTERN_T(x) const char x[]
#define FUNC_TYPE_T(x) static const char x[]
#endif

#if (__STDC_VERSION__ < 201112L) && !defined(static_assert)
#define static_assert(X) \
  extern int(*assertion(void))[!!sizeof(struct { int x : (X) ? 2 : -1; })];
#endif

#ifdef _MSC_VER
#define WEAK_FUNC_DECL(func, fallback)                             \
  __pragma(comment(linker, "/alternatename:" #func "=" #fallback)) \
                                                                   \
      void                                                         \
      fallback(void** instance_ptr, void* tail_call_stack,         \
               wasm_rt_tailcallee_t* next)
#else
#define WEAK_FUNC_DECL(func, fallback)                                        \
  __attribute__((weak)) void func(void** instance_ptr, void* tail_call_stack, \
                                  wasm_rt_tailcallee_t* next)
#endif

static void w2c_snake_update_0(w2c_snake*, f32);
static void w2c_snake_handleKeyAction_0(w2c_snake*, u32, u32);
static void w2c_snake_resize_0(w2c_snake*, u32, u32);
static void w2c_snake_f4(w2c_snake*);
static void w2c_snake_f5(w2c_snake*);
static u32 w2c_snake_f6(w2c_snake*);
static u32 w2c_snake_f7(w2c_snake*, f32, f32, f32);
static u32 w2c_snake_f8(w2c_snake*, f32, f32, f32, f32, f32, f32);
static u32 w2c_snake_f9(w2c_snake*, f32, f32, f32, f32, f32, f32);
static void w2c_snake_f10(w2c_snake*);
static void w2c_snake_f11(w2c_snake*);
static f32 w2c_snake_f12(w2c_snake*);
static f32 w2c_snake_f13(w2c_snake*);
static void w2c_snake_f14(w2c_snake*);
static void w2c_snake_f15(w2c_snake*, u32);
static f32 w2c_snake_f16(w2c_snake*);
static void w2c_snake_f17(w2c_snake*);
static void w2c_snake_f18(w2c_snake*);
static void w2c_snake_f19(w2c_snake*, u32);
static void w2c_snake_f20(w2c_snake*);
static void w2c_snake_f21(w2c_snake*);
static void w2c_snake_f22(w2c_snake*);
static u32 w2c_snake_f23(w2c_snake*, u32);
static u32 w2c_snake_f24(w2c_snake*, u32);
static u32 w2c_snake_f25(w2c_snake*, u32);
static void w2c_snake_f26(w2c_snake*, f32, f32, f32);
static void w2c_snake_f27(w2c_snake*);
static void w2c_snake_f28(w2c_snake*, f32, f32, f32);
static void w2c_snake_f29(w2c_snake*);
static f32 w2c_snake_f30(w2c_snake*);
static f32 w2c_snake_f31(w2c_snake*);
static f32 w2c_snake_f32(w2c_snake*);
static void w2c_snake_f33(w2c_snake*);
static void w2c_snake_f34(w2c_snake*);
static void w2c_snake_f35(w2c_snake*);
static void w2c_snake_f36(w2c_snake*);
static u32 w2c_snake_f37(w2c_snake*);
static f32 w2c_snake_f38(w2c_snake*);
static f32 w2c_snake_f39(w2c_snake*);
static f32 w2c_snake_f40(w2c_snake*);
static f32 w2c_snake_f41(w2c_snake*);
static f32 w2c_snake_f42(w2c_snake*);
static f32 w2c_snake_f43(w2c_snake*);
static u32 w2c_snake_f44(w2c_snake*);
static void w2c_snake_f45(w2c_snake*, u32, u32, u32, u32, u32);
static void w2c_snake_f46(w2c_snake*, f32, f32, f32, f32, u32);
static void w2c_snake_f47(w2c_snake*, u32, u32, u32, u32);
static void w2c_snake_f48(w2c_snake*, f32, f32, f32, u32);
static void w2c_snake_f49(w2c_snake*);
static void w2c_snake_f50(w2c_snake*, f32, f32, f32, u32);
static void w2c_snake_f51(w2c_snake*, u64);
static void w2c_snake_f52(w2c_snake*, u64, f32, f32, u32);
static void w2c_snake_f53(w2c_snake*, u32);
static void w2c_snake_f54(w2c_snake*, u32);
static void w2c_snake_f55(w2c_snake*, u32);
static void w2c_snake_f56(w2c_snake*);
static f32 w2c_snake_f57(w2c_snake*, f32, f32);

FUNC_TYPE_T(w2c_snake_t0) = "\x89\x3a\x3d\x2c\x8f\x4d\x7f\x6d\x6c\x9d\x62\x67\x29\xaf\x3d\x44\x39\x8e\xc3\xf3\xe8\x51\xc1\x99\xb9\xdd\x9f\xd5\x3d\x1f\xd3\xe4";
FUNC_TYPE_T(w2c_snake_t1) = "\x1e\xae\xe1\x36\x90\x48\xec\x4e\x64\xad\xdd\x28\x27\x58\xf2\x7e\x99\xe4\x6d\xde\xa3\x4e\x0b\xe7\x9f\xe0\x73\x04\xe6\x6b\xd8\xad";
FUNC_TYPE_T(w2c_snake_t2) = "\x26\x10\x81\xe2\x21\x43\xd6\x01\x3e\x2d\x2f\x16\x17\x78\x6f\xba\xb3\x2f\x4d\x54\x9b\x8a\xa9\xdd\xbf\x53\x92\x3c\xd3\x71\xc6\xb2";
FUNC_TYPE_T(w2c_snake_t3) = "\x36\xa9\xe7\xf1\xc9\x5b\x82\xff\xb9\x97\x43\xe0\xc5\xc4\xce\x95\xd8\x3c\x9a\x43\x0a\xac\x59\xf8\x4e\xf3\xcb\xfa\xb6\x14\x50\x68";
FUNC_TYPE_T(w2c_snake_t4) = "\x72\xab\x00\xdf\x20\x3d\xce\xa1\xf2\x29\xc7\x9d\x13\x40\x7e\x98\xac\x7d\x41\x4a\x53\x2e\x42\x42\x61\x55\x2e\xaa\xeb\xbe\xc6\x35";
FUNC_TYPE_T(w2c_snake_t5) = "\x41\x4c\xe6\xa0\x95\x43\x11\x0e\x8d\x2a\xd1\x5c\xf2\x31\x7c\x93\x33\x9a\x0c\x9c\x45\x78\x38\x6f\x4c\x85\xa8\x71\xd4\x3d\xc0\xc5";
FUNC_TYPE_T(w2c_snake_t6) = "\xbb\x0f\xfb\x23\x83\xc3\xbc\xea\x18\xef\xbe\x32\x37\xc9\x26\x7c\xec\x29\xeb\x86\x29\xe0\x77\xe7\x5a\x9b\x8c\x7a\x6a\x54\x74\x7e";
FUNC_TYPE_T(w2c_snake_t7) = "\xf4\xba\x4b\xa2\x75\x09\xeb\x70\x4c\x94\x92\xc2\xc5\x75\x1a\x1a\x3e\x87\xc1\xff\x39\xe3\x21\x88\xdb\x22\x48\x89\xae\x98\x2b\xac";
FUNC_TYPE_T(w2c_snake_t8) = "\x07\x80\x96\x7a\x42\xf7\x3e\xe6\x70\x5c\x2f\xac\x83\xf5\x67\xd2\xa2\xa0\x69\x41\x5f\xf8\xe7\x96\x7f\x23\xab\x00\x03\x5f\x4a\x3c";
FUNC_TYPE_T(w2c_snake_t9) = "\xd5\xe6\xdd\x84\x61\x45\x70\x34\xbf\x4e\xbc\xe2\x04\xab\x73\xab\x28\xa5\x57\xe3\x4c\xba\x95\x11\x5d\x70\x93\x72\xe5\x24\x4a\xc4";
FUNC_TYPE_T(w2c_snake_t10) = "\x10\x14\x42\x90\xbf\xa8\x37\x8c\xdc\x81\x9f\x4c\x63\x4e\x62\xb7\x11\x29\xaa\x09\x68\x89\x5f\x5e\x13\x9c\xcc\xe2\xcb\x51\x7a\x78";
FUNC_TYPE_T(w2c_snake_t11) = "\xd2\xc9\xdb\x7a\xb4\x53\x3e\xf4\x2e\x67\x2e\x7b\xd7\xc1\x6e\x17\x6f\xf3\x02\x4e\x74\x61\xd1\x78\x5f\xdd\xc4\xcf\x4c\xa8\x8a\xb4";
FUNC_TYPE_T(w2c_snake_t12) = "\xff\x57\x1f\x83\x74\x67\x5d\x67\x2a\xc8\x0d\x92\x3d\xe8\x47\xa1\x1e\x73\xc7\x03\xa1\xee\x83\x72\x66\xa9\x1c\x9d\xe7\x8c\xdd\xfb";
FUNC_TYPE_T(w2c_snake_t13) = "\xa9\x9b\xd0\x20\x9f\x00\x32\x05\x95\x64\x82\x7b\xdf\x82\xb1\xb0\x9d\x9e\x8b\xef\x74\xe8\xc0\xb0\xbd\x8c\x86\xa1\x6e\xa9\x68\xff";
FUNC_TYPE_T(w2c_snake_t14) = "\x36\xe8\xcd\xcd\x7f\x90\xda\x2c\x26\xd8\x14\xae\x0b\x2f\x96\xbd\x2f\xba\x60\x45\x88\x21\xbf\x78\x71\xf1\x9d\xee\x54\x81\xd3\xc8";
FUNC_TYPE_T(w2c_snake_t15) = "\xb4\x70\x31\x84\xfd\xe8\xcc\x64\xc5\xa6\x1c\xb0\x22\x75\x16\xf3\xa5\xd2\xb8\x72\x36\xa4\x46\xc6\x81\xfe\x02\x71\xe4\x98\x3e\xc6";
FUNC_TYPE_T(w2c_snake_t16) = "\x98\x7e\x2b\xa0\xbc\xda\xe1\x35\x8f\x7d\xe1\xef\xce\x68\x51\x54\x76\xf1\xe0\xfd\xcc\xce\x53\x11\x11\x20\xa1\xeb\xca\x71\x2e\xbe";

static void init_globals(w2c_snake* instance) {
  instance->w2c_memoryRegionLogBytesOffset = 0u;
  instance->w2c_memoryRegionLogBytesN = 2048u;
  instance->w2c_g2 = 2048u;
  instance->w2c_g3 = 63488u;
  instance->w2c_memoryRegionCanvasBytesOffset = 65536u;
  instance->w2c_memoryRegionCanvasBytesN = 0u;
  instance->w2c_g6 = 1u;
  instance->w2c_KEY_ACTION_PRESS = 0u;
  instance->w2c_KEY_ACTION_UP = 1u;
  instance->w2c_KEY_ACTION_DOWN = 2u;
  instance->w2c_KEY_SPACE = 32u;
  instance->w2c_KEY_W = 87u;
  instance->w2c_KEY_w = 119u;
  instance->w2c_ARROW_UP = 151u;
  instance->w2c_KEY_A = 65u;
  instance->w2c_KEY_a = 97u;
  instance->w2c_ARROW_LEFT = 129u;
  instance->w2c_KEY_S = 83u;
  instance->w2c_KEY_s = 115u;
  instance->w2c_ARROW_DOWN = 147u;
  instance->w2c_KEY_D = 68u;
  instance->w2c_KEY_d = 100u;
  instance->w2c_ARROW_RIGHT = 132u;
  instance->w2c_g23 = 1u;
  instance->w2c_g24 = 2u;
  instance->w2c_g25 = 4u;
  instance->w2c_g26 = 8u;
  instance->w2c_g27 = 3u;
  instance->w2c_g28 = 12u;
  instance->w2c_g29 = 300;
  instance->w2c_g30 = 12;
  instance->w2c_g31 = 8;
  instance->w2c_g32 = 0u;
  instance->w2c_g33 = 1u;
  instance->w2c_g34 = 2u;
  instance->w2c_g35 = 3u;
  instance->w2c_g36 = 4279360785u;
  instance->w2c_g37 = 4279334673u;
  instance->w2c_g38 = 4294901998u;
  instance->w2c_g39 = 4294967295u;
  instance->w2c_g40 = 4294945535u;
  instance->w2c_g41 = 4278190080u;
  instance->w2c_g42 = 0.707106769;
  instance->w2c_g43 = 0u;
  instance->w2c_g44 = 0u;
  instance->w2c_g45 = 0u;
  instance->w2c_g46 = -1;
  instance->w2c_g47 = -1;
  instance->w2c_g48 = 0u;
  instance->w2c_g49 = 1;
  instance->w2c_g50 = 0;
  instance->w2c_g51 = 0;
  instance->w2c_g52 = -1;
  instance->w2c_g53 = 0u;
  instance->w2c_g54 = 0u;
  instance->w2c_g55 = 0u;
  instance->w2c_g56 = -1;
  instance->w2c_g57 = -1;
  instance->w2c_g58 = 14971189u;
  instance->w2c_g59 = 7919u;
  instance->w2c_g60 = 0u;
  instance->w2c_g61 = 12u;
  instance->w2c_g62 = 4294967295u;
  instance->w2c_g63 = 4294967295u;
  instance->w2c_g64 = 4294967295u;
  instance->w2c_g65 = 0;
  instance->w2c_g66 = 0;
  instance->w2c_g67 = 0;
  instance->w2c_g68 = 0u;
  instance->w2c_g69 = 32u;
  instance->w2c_g70 = 48u;
  instance->w2c_g71 = 49u;
  instance->w2c_g72 = 50u;
  instance->w2c_g73 = 51u;
  instance->w2c_g74 = 52u;
  instance->w2c_g75 = 53u;
  instance->w2c_g76 = 54u;
  instance->w2c_g77 = 55u;
  instance->w2c_g78 = 56u;
  instance->w2c_g79 = 57u;
  instance->w2c_g80 = 58u;
  instance->w2c_g81 = 65u;
  instance->w2c_g82 = 68u;
  instance->w2c_g83 = 83u;
  instance->w2c_g84 = 87u;
  instance->w2c_g85 = 97u;
  instance->w2c_g86 = 98u;
  instance->w2c_g87 = 99u;
  instance->w2c_g88 = 100u;
  instance->w2c_g89 = 101u;
  instance->w2c_g90 = 102u;
  instance->w2c_g91 = 103u;
  instance->w2c_g92 = 104u;
  instance->w2c_g93 = 105u;
  instance->w2c_g94 = 106u;
  instance->w2c_g95 = 107u;
  instance->w2c_g96 = 108u;
  instance->w2c_g97 = 109u;
  instance->w2c_g98 = 110u;
  instance->w2c_g99 = 111u;
  instance->w2c_g100 = 112u;
  instance->w2c_g101 = 113u;
  instance->w2c_g102 = 114u;
  instance->w2c_g103 = 115u;
  instance->w2c_g104 = 116u;
  instance->w2c_g105 = 117u;
  instance->w2c_g106 = 118u;
  instance->w2c_g107 = 119u;
  instance->w2c_g108 = 120u;
  instance->w2c_g109 = 121u;
  instance->w2c_g110 = 122u;
  instance->w2c_g111 = 0ull;
  instance->w2c_g112 = 4342110275762273280ull;
  instance->w2c_g113 = 4039746526926868480ull;
  instance->w2c_g114 = 9079886045385997312ull;
  instance->w2c_g115 = 4342103601079008256ull;
  instance->w2c_g116 = 2314988902226599936ull;
  instance->w2c_g117 = 4342103635400998400ull;
  instance->w2c_g118 = 4342105824827815936ull;
  instance->w2c_g119 = 289365141412150784ull;
  instance->w2c_g120 = 4342105817315687424ull;
  instance->w2c_g121 = 2026690734748482560ull;
  instance->w2c_g122 = 4774451665011096576ull;
  instance->w2c_g123 = 4486221013981478400ull;
  instance->w2c_g124 = 4342035198389664768ull;
  instance->w2c_g125 = 9079822126638333440ull;
  instance->w2c_g126 = 144680465935269376ull;
  instance->w2c_g127 = 4342106048170179584ull;
  instance->w2c_g128 = 4774451665011098112ull;
  instance->w2c_g129 = 2019873263463177216ull;
  instance->w2c_g130 = 4765391207354483200ull;
  instance->w2c_g131 = 9079822006379217408ull;
  instance->w2c_g132 = 4774451407718072832ull;
  instance->w2c_g133 = 4774486660539105792ull;
  instance->w2c_g134 = 4342105843085491200ull;
  instance->w2c_g135 = 144680604452142592ull;
  instance->w2c_g136 = 4765391414320315904ull;
  instance->w2c_g137 = 4342103617214495744ull;
  instance->w2c_g138 = 1157442765409287680ull;
  instance->w2c_g139 = 4342105843085492736ull;
  instance->w2c_g140 = 145815110936576512ull;
  instance->w2c_g141 = 1157442765815316992ull;
  instance->w2c_g142 = 144117395722732032ull;
  instance->w2c_g143 = 0u;
}

static void init_memories(w2c_snake* instance) {
  wasm_rt_allocate_memory(&instance->w2c_memory, 1, 64, 0);
}

/* export: 'memory' */
wasm_rt_memory_t* w2c_snake_memory(w2c_snake* instance) {
  return &instance->w2c_memory;
}

/* export: 'memoryRegionLogBytesOffset' */
u32* w2c_snake_memoryRegionLogBytesOffset(w2c_snake* instance) {
  return &instance->w2c_memoryRegionLogBytesOffset;
}

/* export: 'memoryRegionLogBytesN' */
u32* w2c_snake_memoryRegionLogBytesN(w2c_snake* instance) {
  return &instance->w2c_memoryRegionLogBytesN;
}

/* export: 'memoryRegionCanvasBytesOffset' */
u32* w2c_snake_memoryRegionCanvasBytesOffset(w2c_snake* instance) {
  return &instance->w2c_memoryRegionCanvasBytesOffset;
}

/* export: 'memoryRegionCanvasBytesN' */
u32* w2c_snake_memoryRegionCanvasBytesN(w2c_snake* instance) {
  return &instance->w2c_memoryRegionCanvasBytesN;
}

/* export: 'KEY_ACTION_PRESS' */
u32* w2c_snake_KEY_ACTION_PRESS(w2c_snake* instance) {
  return &instance->w2c_KEY_ACTION_PRESS;
}

/* export: 'KEY_ACTION_UP' */
u32* w2c_snake_KEY_ACTION_UP(w2c_snake* instance) {
  return &instance->w2c_KEY_ACTION_UP;
}

/* export: 'KEY_ACTION_DOWN' */
u32* w2c_snake_KEY_ACTION_DOWN(w2c_snake* instance) {
  return &instance->w2c_KEY_ACTION_DOWN;
}

/* export: 'KEY_SPACE' */
u32* w2c_snake_KEY_SPACE(w2c_snake* instance) {
  return &instance->w2c_KEY_SPACE;
}

/* export: 'KEY_W' */
u32* w2c_snake_KEY_W(w2c_snake* instance) {
  return &instance->w2c_KEY_W;
}

/* export: 'KEY_w' */
u32* w2c_snake_KEY_w(w2c_snake* instance) {
  return &instance->w2c_KEY_w;
}

/* export: 'ARROW_UP' */
u32* w2c_snake_ARROW_UP(w2c_snake* instance) {
  return &instance->w2c_ARROW_UP;
}

/* export: 'KEY_A' */
u32* w2c_snake_KEY_A(w2c_snake* instance) {
  return &instance->w2c_KEY_A;
}

/* export: 'KEY_a' */
u32* w2c_snake_KEY_a(w2c_snake* instance) {
  return &instance->w2c_KEY_a;
}

/* export: 'ARROW_LEFT' */
u32* w2c_snake_ARROW_LEFT(w2c_snake* instance) {
  return &instance->w2c_ARROW_LEFT;
}

/* export: 'KEY_S' */
u32* w2c_snake_KEY_S(w2c_snake* instance) {
  return &instance->w2c_KEY_S;
}

/* export: 'KEY_s' */
u32* w2c_snake_KEY_s(w2c_snake* instance) {
  return &instance->w2c_KEY_s;
}

/* export: 'ARROW_DOWN' */
u32* w2c_snake_ARROW_DOWN(w2c_snake* instance) {
  return &instance->w2c_ARROW_DOWN;
}

/* export: 'KEY_D' */
u32* w2c_snake_KEY_D(w2c_snake* instance) {
  return &instance->w2c_KEY_D;
}

/* export: 'KEY_d' */
u32* w2c_snake_KEY_d(w2c_snake* instance) {
  return &instance->w2c_KEY_d;
}

/* export: 'ARROW_RIGHT' */
u32* w2c_snake_ARROW_RIGHT(w2c_snake* instance) {
  return &instance->w2c_ARROW_RIGHT;
}

/* export: 'update' */
void w2c_snake_update(w2c_snake* instance, f32 var_p0) {
  w2c_snake_update_0(instance, var_p0);
}

/* export: 'handleKeyAction' */
void w2c_snake_handleKeyAction(w2c_snake* instance, u32 var_p0, u32 var_p1) {
  w2c_snake_handleKeyAction_0(instance, var_p0, var_p1);
}

/* export: 'resize' */
void w2c_snake_resize(w2c_snake* instance, u32 var_p0, u32 var_p1) {
  w2c_snake_resize_0(instance, var_p0, var_p1);
}

static void init_instance_import(w2c_snake* instance, struct w2c_imports* w2c_imports_instance) {
  instance->w2c_imports_instance = w2c_imports_instance;
}

void wasm2c_snake_instantiate(w2c_snake* instance, struct w2c_imports* w2c_imports_instance) {
  assert(wasm_rt_is_initialized());
  init_instance_import(instance, w2c_imports_instance);
  init_globals(instance);
  init_memories(instance);
}

void wasm2c_snake_free(w2c_snake* instance) {
  wasm_rt_free_memory(&instance->w2c_memory);
}

wasm_rt_func_type_t wasm2c_snake_get_func_type(uint32_t param_count, uint32_t result_count, ...) {
  va_list args;
  
  if (param_count == 1 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t0;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32) {
      va_end(args);
      return w2c_snake_t1;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t2;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 0) {
    va_start(args, result_count);
    if (true) {
      va_end(args);
      return w2c_snake_t3;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t4;
    }
    va_end(args);
  }
  
  if (param_count == 3 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t5;
    }
    va_end(args);
  }
  
  if (param_count == 6 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t6;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32) {
      va_end(args);
      return w2c_snake_t7;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t8;
    }
    va_end(args);
  }
  
  if (param_count == 3 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32) {
      va_end(args);
      return w2c_snake_t9;
    }
    va_end(args);
  }
  
  if (param_count == 5 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t10;
    }
    va_end(args);
  }
  
  if (param_count == 5 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t11;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t12;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t13;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I64) {
      va_end(args);
      return w2c_snake_t14;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I64 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_snake_t15;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32 && va_arg(args, wasm_rt_type_t) == WASM_RT_F32) {
      va_end(args);
      return w2c_snake_t16;
    }
    va_end(args);
  }
  
  return NULL;
}

void w2c_snake_update_0(w2c_snake* instance, f32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0, var_f1, var_f2;
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g32;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f4(instance);
    var_i0 = instance->w2c_g33;
    instance->w2c_g45 = var_i0;
    goto var_Bfunc;
  }
  var_f0 = instance->w2c_g46;
  instance->w2c_g47 = var_f0;
  var_f0 = var_p0;
  instance->w2c_g46 = var_f0;
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g33;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f20(instance);
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g34;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f5(instance);
    var_f0 = w2c_snake_f12(instance);
    var_f1 = w2c_snake_f13(instance);
    var_f2 = instance->w2c_g31;
    var_i0 = w2c_snake_f7(instance, var_f0, var_f1, var_f2);
    if (var_i0) {
      w2c_snake_f17(instance);
      w2c_snake_f11(instance);
      w2c_snake_f10(instance);
    }
    w2c_snake_f18(instance);
    var_i0 = w2c_snake_f6(instance);
    if (var_i0) {
      var_i0 = instance->w2c_g35;
      instance->w2c_g45 = var_i0;
    }
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g35;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f21(instance);
    goto var_Bfunc;
  }
  var_Bfunc:;
  FUNC_EPILOGUE;
}

void w2c_snake_handleKeyAction_0(w2c_snake* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  f32 var_f0, var_f1;
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g33;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f4(instance);
    var_i0 = instance->w2c_g34;
    instance->w2c_g45 = var_i0;
    w2c_snake_f11(instance);
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g35;
  var_i0 = var_i0 == var_i1;
  var_i1 = var_p1;
  var_i2 = instance->w2c_g69;
  var_i1 = var_i1 == var_i2;
  var_i0 &= var_i1;
  if (var_i0) {
    w2c_snake_f4(instance);
    var_i0 = instance->w2c_g34;
    instance->w2c_g45 = var_i0;
    w2c_snake_f11(instance);
    goto var_Bfunc;
  }
  var_i0 = var_p1;
  var_i1 = 5u;
  var_i0 >>= (var_i1 & 31);
  var_l2 = var_i0;
  var_i0 = var_l2;
  var_i1 = 2u;
  var_i0 = var_i0 < var_i1;
  var_i1 = var_l2;
  var_i2 = 4u;
  var_i1 = var_i1 > var_i2;
  var_i0 |= var_i1;
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_p1;
  var_i1 = 31u;
  var_i0 &= var_i1;
  var_i1 = 128u;
  var_i0 |= var_i1;
  var_l3 = var_i0;
  var_i0 = var_l3;
  var_i1 = instance->w2c_ARROW_UP;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g25;
    var_l4 = var_i0;
  }
  var_i0 = var_l3;
  var_i1 = instance->w2c_ARROW_LEFT;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g24;
    var_l4 = var_i0;
  }
  var_i0 = var_l3;
  var_i1 = instance->w2c_ARROW_DOWN;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g26;
    var_l4 = var_i0;
  }
  var_i0 = var_l3;
  var_i1 = instance->w2c_ARROW_RIGHT;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g23;
    var_l4 = var_i0;
  }
  var_i0 = var_p0;
  var_i1 = instance->w2c_KEY_ACTION_PRESS;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = var_l4;
    instance->w2c_g48 = var_i0;
  }
  var_i0 = var_p0;
  var_i1 = instance->w2c_KEY_ACTION_DOWN;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g27;
    var_i1 = var_l4;
    var_i0 &= var_i1;
    if (var_i0) {
      var_i0 = instance->w2c_g48;
      var_i1 = instance->w2c_g28;
      var_i0 &= var_i1;
      instance->w2c_g48 = var_i0;
    }
    var_i0 = instance->w2c_g28;
    var_i1 = var_l4;
    var_i0 &= var_i1;
    if (var_i0) {
      var_i0 = instance->w2c_g48;
      var_i1 = instance->w2c_g27;
      var_i0 &= var_i1;
      instance->w2c_g48 = var_i0;
    }
    var_i0 = instance->w2c_g48;
    var_i1 = var_l4;
    var_i0 |= var_i1;
    instance->w2c_g48 = var_i0;
  }
  var_i0 = var_p0;
  var_i1 = instance->w2c_KEY_ACTION_UP;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g48;
    var_i1 = 15u;
    var_i2 = var_l4;
    var_i1 ^= var_i2;
    var_i0 &= var_i1;
    instance->w2c_g48 = var_i0;
  }
  var_i0 = instance->w2c_g48;
  var_i1 = instance->w2c_g25;
  var_i0 &= var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g48;
    var_i1 = instance->w2c_g24;
    var_i0 &= var_i1;
    if (var_i0) {
      var_f0 = -1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g49 = var_f0;
      var_f0 = -1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g50 = var_f0;
      goto var_Bfunc;
    }
    var_i0 = instance->w2c_g48;
    var_i1 = instance->w2c_g23;
    var_i0 &= var_i1;
    if (var_i0) {
      var_f0 = 1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g49 = var_f0;
      var_f0 = -1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g50 = var_f0;
      goto var_Bfunc;
    }
    var_f0 = 0;
    instance->w2c_g49 = var_f0;
    var_f0 = -1;
    instance->w2c_g50 = var_f0;
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g48;
  var_i1 = instance->w2c_g26;
  var_i0 &= var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g48;
    var_i1 = instance->w2c_g24;
    var_i0 &= var_i1;
    if (var_i0) {
      var_f0 = -1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g49 = var_f0;
      var_f0 = 1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g50 = var_f0;
      goto var_Bfunc;
    }
    var_i0 = instance->w2c_g48;
    var_i1 = instance->w2c_g23;
    var_i0 &= var_i1;
    if (var_i0) {
      var_f0 = 1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g49 = var_f0;
      var_f0 = 1;
      var_f1 = instance->w2c_g42;
      var_f0 *= var_f1;
      instance->w2c_g50 = var_f0;
      goto var_Bfunc;
    }
    var_f0 = 0;
    instance->w2c_g49 = var_f0;
    var_f0 = 1;
    instance->w2c_g50 = var_f0;
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g48;
  var_i1 = instance->w2c_g24;
  var_i0 &= var_i1;
  if (var_i0) {
    var_f0 = -1;
    instance->w2c_g49 = var_f0;
    var_f0 = 0;
    instance->w2c_g50 = var_f0;
    goto var_Bfunc;
  }
  var_i0 = instance->w2c_g48;
  var_i1 = instance->w2c_g23;
  var_i0 &= var_i1;
  if (var_i0) {
    var_f0 = 1;
    instance->w2c_g49 = var_f0;
    var_f0 = 0;
    instance->w2c_g50 = var_f0;
    goto var_Bfunc;
  }
  var_Bfunc:;
  FUNC_EPILOGUE;
}

void w2c_snake_resize_0(w2c_snake* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  instance->w2c_g43 = var_i0;
  var_i0 = var_p1;
  instance->w2c_g44 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 *= var_i1;
  var_i1 = 4u;
  var_i0 *= var_i1;
  instance->w2c_memoryRegionCanvasBytesN = var_i0;
  var_i0 = instance->w2c_memoryRegionCanvasBytesN;
  var_i1 = 65536u;
  var_i0 = DIV_U(var_i0, var_i1);
  var_i1 = 2u;
  var_i0 += var_i1;
  var_i1 = instance->w2c_memory.pages;
  var_i0 -= var_i1;
  var_l2 = var_i0;
  var_i0 = var_l2;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
  if (var_i0) {
    var_i0 = var_l2;
    var_i0 = wasm_rt_grow_memory(&instance->w2c_memory, var_i0);
  }
  w2c_snake_f49(instance);
  var_i0 = instance->w2c_g45;
  var_i1 = instance->w2c_g34;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    w2c_snake_f14(instance);
  }
  FUNC_EPILOGUE;
}

void w2c_snake_f4(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0, var_f1, var_f2;
  var_i0 = instance->w2c_g43;
  var_i1 = instance->w2c_g44;
  w2c_snake_resize_0(instance, var_i0, var_i1);
  w2c_snake_f22(instance);
  var_f0 = 0;
  instance->w2c_g51 = var_f0;
  var_f0 = 0;
  instance->w2c_g52 = var_f0;
  w2c_snake_f10(instance);
  var_i0 = instance->w2c_g43;
  var_f0 = (f32)(s32)(var_i0);
  var_f1 = 2;
  var_f0 /= var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f2 = 0;
  w2c_snake_f26(instance, var_f0, var_f1, var_f2);
  var_f0 = 1;
  instance->w2c_g49 = var_f0;
  var_f0 = 0;
  instance->w2c_g50 = var_f0;
  var_i0 = 0u;
  instance->w2c_g53 = var_i0;
  var_i0 = 0u;
  instance->w2c_g54 = var_i0;
  var_i0 = 0u;
  instance->w2c_g55 = var_i0;
  var_f0 = -1;
  instance->w2c_g56 = var_f0;
  var_f0 = -1;
  instance->w2c_g57 = var_f0;
  var_i0 = 0u;
  w2c_snake_f15(instance, var_i0);
  FUNC_EPILOGUE;
}

void w2c_snake_f5(w2c_snake* instance) {
  f32 var_l0 = 0, var_l1 = 0, var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i3;
  f32 var_f0, var_f1, var_f2;
  var_f0 = instance->w2c_g29;
  var_f1 = instance->w2c_g46;
  var_f2 = instance->w2c_g47;
  var_f1 -= var_f2;
  var_f2 = 0.00100000005;
  var_f1 *= var_f2;
  var_f0 *= var_f1;
  var_l0 = var_f0;
  var_f0 = w2c_snake_f38(instance);
  var_f1 = instance->w2c_g49;
  var_f2 = var_l0;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  var_i1 = instance->w2c_g43;
  var_f1 = (f32)(s32)(var_i1);
  var_f0 = w2c_snake_f57(instance, var_f0, var_f1);
  var_l1 = var_f0;
  var_f0 = w2c_snake_f39(instance);
  var_f1 = instance->w2c_g50;
  var_f2 = var_l0;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f0 = w2c_snake_f57(instance, var_f0, var_f1);
  var_l2 = var_f0;
  var_L1: 
    var_f0 = instance->w2c_g51;
    var_f1 = instance->w2c_g52;
    var_i0 = var_f0 <= var_f1;
    if (var_i0) {goto var_B0;}
    var_f0 = instance->w2c_g51;
    var_f1 = w2c_snake_f43(instance);
    var_f0 -= var_f1;
    instance->w2c_g51 = var_f0;
    var_f0 = w2c_snake_f41(instance);
    var_f1 = w2c_snake_f42(instance);
    var_f2 = instance->w2c_g30;
    var_i3 = instance->w2c_g41;
    w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
    w2c_snake_f29(instance);
  var_B0:;
  var_f0 = w2c_snake_f41(instance);
  var_f1 = w2c_snake_f42(instance);
  var_f2 = instance->w2c_g30;
  var_i3 = instance->w2c_g37;
  w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  var_f0 = instance->w2c_g51;
  var_f1 = var_l0;
  var_f0 += var_f1;
  instance->w2c_g51 = var_f0;
  var_f0 = w2c_snake_f38(instance);
  var_f1 = w2c_snake_f39(instance);
  var_f2 = instance->w2c_g30;
  var_i3 = instance->w2c_g37;
  w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  var_f0 = var_l1;
  var_f1 = var_l2;
  var_f2 = instance->w2c_g30;
  var_i3 = instance->w2c_g36;
  w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  var_f0 = var_l1;
  var_f1 = var_l2;
  var_f2 = var_l0;
  w2c_snake_f28(instance, var_f0, var_f1, var_f2);
  FUNC_EPILOGUE;
}

u32 w2c_snake_f6(w2c_snake* instance) {
  f32 var_l0 = 0, var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0, var_f1, var_f2;
  w2c_snake_f36(instance);
  var_L0: 
    var_f0 = w2c_snake_f30(instance);
    var_l0 = var_f0;
    var_f0 = w2c_snake_f31(instance);
    var_l1 = var_f0;
    var_f0 = var_l0;
    var_f1 = var_l1;
    var_f2 = instance->w2c_g30;
    var_i0 = w2c_snake_f7(instance, var_f0, var_f1, var_f2);
    if (var_i0) {
      var_i0 = 1u;
      goto var_Bfunc;
    }
    w2c_snake_f33(instance);
    var_i0 = w2c_snake_f37(instance);
    var_i1 = 0u;
    var_i0 = var_i0 == var_i1;
    if (var_i0) {goto var_L0;}
  var_i0 = 0u;
  goto var_Bfunc;
  var_Bfunc:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_snake_f7(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0, var_f1, var_f2, var_f3, var_f4, var_f5, var_f6;
  var_f0 = w2c_snake_f38(instance);
  var_f1 = w2c_snake_f39(instance);
  var_f2 = var_p0;
  var_f3 = var_p1;
  var_f4 = instance->w2c_g49;
  var_f5 = instance->w2c_g50;
  var_i0 = w2c_snake_f9(instance, var_f0, var_f1, var_f2, var_f3, var_f4, var_f5);
  var_f1 = w2c_snake_f38(instance);
  var_f2 = w2c_snake_f39(instance);
  var_f3 = instance->w2c_g30;
  var_f4 = var_p0;
  var_f5 = var_p1;
  var_f6 = var_p2;
  var_i1 = w2c_snake_f8(instance, var_f1, var_f2, var_f3, var_f4, var_f5, var_f6);
  var_i0 &= var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_snake_f8(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2, f32 var_p3, f32 var_p4, f32 var_p5) {
  f32 var_l6 = 0, var_l7 = 0, var_l8 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0, var_f1, var_f2;
  var_f0 = var_p3;
  var_f1 = var_p0;
  var_f0 -= var_f1;
  var_f0 = wasm_fabsf(var_f0);
  var_l6 = var_f0;
  var_f0 = var_p4;
  var_f1 = var_p1;
  var_f0 -= var_f1;
  var_f0 = wasm_fabsf(var_f0);
  var_l7 = var_f0;
  var_f0 = var_p2;
  var_f1 = var_p5;
  var_f0 += var_f1;
  var_l8 = var_f0;
  var_f0 = var_l6;
  var_f1 = var_l6;
  var_f0 *= var_f1;
  var_f1 = var_l7;
  var_f2 = var_l7;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  var_f1 = var_l8;
  var_f2 = var_l8;
  var_f1 *= var_f2;
  var_i0 = var_f0 < var_f1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_snake_f9(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2, f32 var_p3, f32 var_p4, f32 var_p5) {
  f32 var_l6 = 0, var_l7 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0, var_f1, var_f2;
  var_f0 = var_p2;
  var_f1 = var_p0;
  var_f0 -= var_f1;
  var_l6 = var_f0;
  var_f0 = var_p3;
  var_f1 = var_p1;
  var_f0 -= var_f1;
  var_l7 = var_f0;
  var_f0 = var_p4;
  var_f1 = var_l6;
  var_f0 *= var_f1;
  var_f1 = var_p5;
  var_f2 = var_l7;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  var_f1 = 0;
  var_i0 = var_f0 > var_f1;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_snake_f10(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i2, var_i3;
  f32 var_f0, var_f1, var_f2;
  var_f0 = instance->w2c_g52;
  var_f1 = 0.0500000007;
  var_i2 = instance->w2c_g43;
  var_i3 = instance->w2c_g44;
  var_i2 += var_i3;
  var_f2 = (f32)(s32)(var_i2);
  var_f1 *= var_f2;
  var_f0 += var_f1;
  instance->w2c_g52 = var_f0;
  FUNC_EPILOGUE;
}

void w2c_snake_f11(w2c_snake* instance) {
  f32 var_l0 = 0, var_l1 = 0, var_l2 = 0, var_l3 = 0, var_l4 = 0, var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i3;
  f32 var_f0, var_f1, var_f2, var_f3, var_f4, var_f5;
  var_f0 = w2c_snake_f12(instance);
  var_l2 = var_f0;
  var_f0 = w2c_snake_f13(instance);
  var_l3 = var_f0;
  var_L0: 
    var_f0 = w2c_snake_f16(instance);
    instance->w2c_g56 = var_f0;
    var_f0 = w2c_snake_f16(instance);
    instance->w2c_g57 = var_f0;
    var_f0 = w2c_snake_f12(instance);
    var_l0 = var_f0;
    var_f0 = w2c_snake_f13(instance);
    var_l1 = var_f0;
    w2c_snake_f36(instance);
    var_L2: 
      var_f0 = w2c_snake_f30(instance);
      var_l4 = var_f0;
      var_f0 = w2c_snake_f31(instance);
      var_l5 = var_f0;
      var_f0 = var_l0;
      var_f1 = var_l1;
      var_f2 = instance->w2c_g31;
      var_f3 = var_l4;
      var_f4 = var_l5;
      var_f5 = instance->w2c_g30;
      var_i0 = w2c_snake_f8(instance, var_f0, var_f1, var_f2, var_f3, var_f4, var_f5);
      if (var_i0) {goto var_L0;}
      w2c_snake_f33(instance);
      var_i0 = w2c_snake_f37(instance);
      if (var_i0) {goto var_B1;}
      goto var_L2;
    var_B1:;
  var_f0 = var_l2;
  var_f1 = -1;
  var_i0 = var_f0 != var_f1;
  if (var_i0) {
    var_f0 = var_l2;
    var_f1 = var_l3;
    var_f2 = instance->w2c_g31;
    var_i3 = instance->w2c_g41;
    w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  }
  w2c_snake_f14(instance);
  FUNC_EPILOGUE;
}

f32 w2c_snake_f12(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i1;
  f32 var_f0, var_f1;
  var_f0 = instance->w2c_g56;
  var_i1 = instance->w2c_g43;
  var_f1 = (f32)(var_i1);
  var_f0 *= var_f1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f13(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i1;
  f32 var_f0, var_f1;
  var_f0 = instance->w2c_g57;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(var_i1);
  var_f0 *= var_f1;
  FUNC_EPILOGUE;
  return var_f0;
}

void w2c_snake_f14(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i3;
  f32 var_f0, var_f1, var_f2, var_f3;
  var_f0 = w2c_snake_f12(instance);
  var_f1 = w2c_snake_f13(instance);
  var_f2 = instance->w2c_g31;
  var_i3 = instance->w2c_g38;
  w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  var_f0 = w2c_snake_f12(instance);
  var_f1 = 0.200000003;
  var_f2 = instance->w2c_g31;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  var_f1 = w2c_snake_f13(instance);
  var_f2 = -0.200000003;
  var_f3 = instance->w2c_g31;
  var_f2 *= var_f3;
  var_f1 += var_f2;
  var_f2 = 0.400000006;
  var_f3 = instance->w2c_g31;
  var_f2 *= var_f3;
  var_i3 = instance->w2c_g39;
  w2c_snake_f48(instance, var_f0, var_f1, var_f2, var_i3);
  FUNC_EPILOGUE;
}

void w2c_snake_f15(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = instance->w2c_g59;
  var_i0 *= var_i1;
  var_p0 = var_i0;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = instance->w2c_g59;
    var_p0 = var_i0;
  }
  var_i0 = var_p0;
  instance->w2c_g60 = var_i0;
  FUNC_EPILOGUE;
}

f32 w2c_snake_f16(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  f32 var_f0, var_f1;
  var_i0 = instance->w2c_g60;
  var_i1 = instance->w2c_g58;
  var_i0 *= var_i1;
  instance->w2c_g60 = var_i0;
  var_i0 = 1065353216u;
  var_i1 = instance->w2c_g60;
  var_i2 = 9u;
  var_i1 >>= (var_i2 & 31);
  var_i0 |= var_i1;
  var_f0 = f32_reinterpret_i32(var_i0);
  var_f1 = 1;
  var_f0 -= var_f1;
  FUNC_EPILOGUE;
  return var_f0;
}

void w2c_snake_f17(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g41;
  w2c_snake_f19(instance, var_i0);
  var_i0 = instance->w2c_g55;
  var_i1 = 1u;
  var_i0 += var_i1;
  instance->w2c_g55 = var_i0;
  var_i0 = instance->w2c_g55;
  var_i1 = 10u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = 0u;
    instance->w2c_g55 = var_i0;
    var_i0 = instance->w2c_g54;
    var_i1 = 1u;
    var_i0 += var_i1;
    instance->w2c_g54 = var_i0;
    var_i0 = instance->w2c_g54;
    var_i1 = 10u;
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_i0 = 0u;
      instance->w2c_g54 = var_i0;
      var_i0 = instance->w2c_g53;
      var_i1 = 1u;
      var_i0 += var_i1;
      instance->w2c_g53 = var_i0;
    }
  }
  var_i0 = instance->w2c_g40;
  w2c_snake_f19(instance, var_i0);
  FUNC_EPILOGUE;
}

void w2c_snake_f18(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g40;
  w2c_snake_f19(instance, var_i0);
  FUNC_EPILOGUE;
}

void w2c_snake_f19(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i3;
  u64 var_j0;
  f32 var_f0, var_f1, var_f2;
  var_f0 = 16;
  var_f1 = 16;
  var_f2 = 16;
  var_i3 = var_p0;
  w2c_snake_f50(instance, var_f0, var_f1, var_f2, var_i3);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g124;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_i0 = instance->w2c_g53;
  w2c_snake_f53(instance, var_i0);
  var_i0 = instance->w2c_g54;
  w2c_snake_f53(instance, var_i0);
  var_i0 = instance->w2c_g55;
  w2c_snake_f53(instance, var_i0);
  FUNC_EPILOGUE;
}

void w2c_snake_f20(w2c_snake* instance) {
  f32 var_l0 = 0, var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i3;
  u64 var_j0;
  f32 var_f0, var_f1, var_f2, var_f3;
  var_f0 = 29;
  var_l0 = var_f0;
  var_f0 = 16;
  var_l1 = var_f0;
  var_i0 = instance->w2c_g43;
  var_f0 = (f32)(s32)(var_i0);
  var_f1 = 2;
  var_f0 /= var_f1;
  var_f1 = var_l0;
  var_f2 = var_l1;
  var_f1 *= var_f2;
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f0 -= var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f2 = var_l1;
  var_f3 = 2;
  var_f2 /= var_f3;
  var_f1 -= var_f2;
  var_f2 = var_l1;
  var_i3 = instance->w2c_g40;
  w2c_snake_f50(instance, var_f0, var_f1, var_f2, var_i3);
  var_j0 = instance->w2c_g135;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g130;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g141;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g139;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g124;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g128;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  FUNC_EPILOGUE;
}

void w2c_snake_f21(w2c_snake* instance) {
  f32 var_l0 = 0, var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i3;
  u64 var_j0;
  f32 var_f0, var_f1, var_f2, var_f3;
  var_f0 = 10;
  var_l0 = var_f0;
  var_f0 = 16;
  var_l1 = var_f0;
  var_i0 = instance->w2c_g43;
  var_f0 = (f32)(s32)(var_i0);
  var_f1 = 2;
  var_f0 /= var_f1;
  var_f1 = var_l0;
  var_f2 = var_l1;
  var_f1 *= var_f2;
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f0 -= var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f2 = var_l1;
  var_f3 = 4;
  var_f2 *= var_f3;
  var_f1 -= var_f2;
  var_f2 = var_l1;
  var_i3 = instance->w2c_g40;
  w2c_snake_f50(instance, var_f0, var_f1, var_f2, var_i3);
  var_j0 = instance->w2c_g127;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g132;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g140;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g142;
  w2c_snake_f51(instance, var_j0);
  var_f0 = 15;
  var_l0 = var_f0;
  var_f0 = 24;
  var_l1 = var_f0;
  var_i0 = instance->w2c_g43;
  var_f0 = (f32)(s32)(var_i0);
  var_f1 = 2;
  var_f0 /= var_f1;
  var_f1 = var_l0;
  var_f2 = var_l1;
  var_f1 *= var_f2;
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f0 -= var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f2 = var_l1;
  var_f3 = 0;
  var_f2 *= var_f3;
  var_f1 += var_f2;
  var_f2 = var_l1;
  var_i3 = instance->w2c_g40;
  w2c_snake_f50(instance, var_f0, var_f1, var_f2, var_i3);
  var_j0 = instance->w2c_g126;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g129;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g133;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g131;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g124;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_i0 = instance->w2c_g53;
  w2c_snake_f53(instance, var_i0);
  var_i0 = instance->w2c_g54;
  w2c_snake_f53(instance, var_i0);
  var_i0 = instance->w2c_g55;
  w2c_snake_f53(instance, var_i0);
  var_f0 = 22;
  var_l0 = var_f0;
  var_f0 = 16;
  var_l1 = var_f0;
  var_i0 = instance->w2c_g43;
  var_f0 = (f32)(s32)(var_i0);
  var_f1 = 2;
  var_f0 /= var_f1;
  var_f1 = var_l0;
  var_f2 = var_l1;
  var_f1 *= var_f2;
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f0 -= var_f1;
  var_i1 = instance->w2c_g44;
  var_f1 = (f32)(s32)(var_i1);
  var_f2 = 2;
  var_f1 /= var_f2;
  var_f2 = var_l1;
  var_f3 = -4;
  var_f2 *= var_f3;
  var_f1 -= var_f2;
  var_f2 = var_l1;
  var_i3 = instance->w2c_g40;
  w2c_snake_f50(instance, var_f0, var_f1, var_f2, var_i3);
  var_j0 = instance->w2c_g135;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g135;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g124;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g134;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g111;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g125;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g137;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g122;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g136;
  w2c_snake_f51(instance, var_j0);
  var_j0 = instance->w2c_g138;
  w2c_snake_f51(instance, var_j0);
  FUNC_EPILOGUE;
}

void w2c_snake_f22(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g2;
  instance->w2c_g62 = var_i0;
  var_i0 = instance->w2c_g2;
  instance->w2c_g63 = var_i0;
  var_i0 = instance->w2c_g2;
  instance->w2c_g64 = var_i0;
  FUNC_EPILOGUE;
}

u32 w2c_snake_f23(w2c_snake* instance, u32 var_p0) {
  u32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  var_i0 = instance->w2c_g3;
  var_i1 = instance->w2c_g3;
  var_i2 = instance->w2c_g61;
  var_i1 = REM_U(var_i1, var_i2);
  var_i0 -= var_i1;
  var_l1 = var_i0;
  var_i0 = var_p0;
  var_i1 = instance->w2c_g2;
  var_i0 -= var_i1;
  var_p0 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_l1;
  var_i0 = REM_U(var_i0, var_i1);
  var_p0 = var_i0;
  var_i0 = var_p0;
  var_i1 = instance->w2c_g2;
  var_i0 += var_i1;
  var_p0 = var_i0;
  var_i0 = var_p0;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_snake_f24(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = instance->w2c_g61;
  var_i0 += var_i1;
  var_p0 = var_i0;
  var_i0 = var_p0;
  var_i0 = w2c_snake_f23(instance, var_i0);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_snake_f25(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = instance->w2c_g61;
  var_i0 -= var_i1;
  var_p0 = var_i0;
  var_i0 = var_p0;
  var_i0 = w2c_snake_f23(instance, var_i0);
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_snake_f26(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f1;
  var_i0 = instance->w2c_g62;
  var_i1 = 0u;
  var_i0 += var_i1;
  var_f1 = var_p0;
  f32_store(&instance->w2c_memory, (u64)(var_i0), var_f1);
  var_i0 = instance->w2c_g62;
  var_i1 = 4u;
  var_i0 += var_i1;
  var_f1 = var_p1;
  f32_store(&instance->w2c_memory, (u64)(var_i0), var_f1);
  var_i0 = instance->w2c_g62;
  var_i1 = 8u;
  var_i0 += var_i1;
  var_f1 = var_p2;
  f32_store(&instance->w2c_memory, (u64)(var_i0), var_f1);
  FUNC_EPILOGUE;
}

void w2c_snake_f27(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g62;
  var_i0 = w2c_snake_f24(instance, var_i0);
  instance->w2c_g62 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f28(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2) {
  FUNC_PROLOGUE;
  f32 var_f0, var_f1, var_f2;
  w2c_snake_f27(instance);
  var_f0 = var_p0;
  var_f1 = var_p1;
  var_f2 = var_p2;
  w2c_snake_f26(instance, var_f0, var_f1, var_f2);
  FUNC_EPILOGUE;
}

void w2c_snake_f29(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g63;
  var_i0 = w2c_snake_f24(instance, var_i0);
  instance->w2c_g63 = var_i0;
  FUNC_EPILOGUE;
}

f32 w2c_snake_f30(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_f0 = f32_load(&instance->w2c_memory, (u64)(var_i0));
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f31(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_i1 = 4u;
  var_i0 += var_i1;
  var_f0 = f32_load(&instance->w2c_memory, (u64)(var_i0));
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f32(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_i1 = 8u;
  var_i0 += var_i1;
  var_f0 = f32_load(&instance->w2c_memory, (u64)(var_i0));
  FUNC_EPILOGUE;
  return var_f0;
}

void w2c_snake_f33(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g64;
  var_i0 = w2c_snake_f24(instance, var_i0);
  instance->w2c_g64 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f34(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g64;
  var_i0 = w2c_snake_f25(instance, var_i0);
  instance->w2c_g64 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f35(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g62;
  instance->w2c_g64 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f36(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g63;
  instance->w2c_g64 = var_i0;
  FUNC_EPILOGUE;
}

u32 w2c_snake_f37(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g64;
  var_i1 = instance->w2c_g62;
  var_i0 = var_i0 == var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

f32 w2c_snake_f38(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f35(instance);
  var_f0 = w2c_snake_f30(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f39(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f35(instance);
  var_f0 = w2c_snake_f31(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f40(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f35(instance);
  var_f0 = w2c_snake_f32(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f41(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f36(instance);
  var_f0 = w2c_snake_f30(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f42(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f36(instance);
  var_f0 = w2c_snake_f31(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

f32 w2c_snake_f43(w2c_snake* instance) {
  u32 var_l0 = 0;
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_i0 = instance->w2c_g64;
  var_l0 = var_i0;
  w2c_snake_f36(instance);
  var_f0 = w2c_snake_f32(instance);
  var_l1 = var_f0;
  var_i0 = var_l0;
  instance->w2c_g64 = var_i0;
  var_f0 = var_l1;
  FUNC_EPILOGUE;
  return var_f0;
}

u32 w2c_snake_f44(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g43;
  var_i1 = instance->w2c_g44;
  var_i0 *= var_i1;
  var_i1 = 4u;
  var_i0 *= var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_snake_f45(w2c_snake* instance, u32 var_p0, u32 var_p1, u32 var_p2, u32 var_p3, u32 var_p4) {
  u32 var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  var_i0 = var_p0;
  var_l6 = var_i0;
  var_i0 = var_p1;
  var_l7 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_p2;
  var_i0 += var_i1;
  var_l8 = var_i0;
  var_i0 = var_p1;
  var_i1 = var_p3;
  var_i0 += var_i1;
  var_l9 = var_i0;
  var_i0 = var_l8;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l9;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l6;
  var_i1 = instance->w2c_g43;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l7;
  var_i1 = instance->w2c_g44;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l6;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_l6 = var_i0;
  }
  var_i0 = var_l7;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_l7 = var_i0;
  }
  var_i0 = var_l8;
  var_i1 = instance->w2c_g43;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    var_i0 = instance->w2c_g43;
    var_i1 = 1u;
    var_i0 -= var_i1;
    var_l8 = var_i0;
  }
  var_i0 = var_l9;
  var_i1 = instance->w2c_g44;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    var_i0 = instance->w2c_g44;
    var_i1 = 1u;
    var_i0 -= var_i1;
    var_l9 = var_i0;
  }
  var_L8: 
    var_i0 = var_l6;
    var_p0 = var_i0;
    var_i0 = instance->w2c_memoryRegionCanvasBytesOffset;
    var_i1 = instance->w2c_g44;
    var_i2 = var_p1;
    var_i1 -= var_i2;
    var_i2 = instance->w2c_g43;
    var_i1 *= var_i2;
    var_i2 = var_p0;
    var_i1 += var_i2;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_l5 = var_i0;
    var_L9: 
      var_i0 = var_l5;
      var_i1 = var_p4;
      i32_store(&instance->w2c_memory, (u64)(var_i0), var_i1);
      var_i0 = var_l5;
      var_i1 = 4u;
      var_i0 += var_i1;
      var_l5 = var_i0;
      var_i0 = var_p0;
      var_i1 = 1u;
      var_i0 += var_i1;
      var_p0 = var_i0;
      var_i0 = var_p0;
      var_i1 = var_l8;
      var_i0 = var_i0 != var_i1;
      if (var_i0) {goto var_L9;}
    var_i0 = var_p1;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_p1 = var_i0;
    var_i0 = var_p1;
    var_i1 = var_l9;
    var_i0 = var_i0 != var_i1;
    if (var_i0) {goto var_L8;}
  var_Bfunc:;
  FUNC_EPILOGUE;
}

void w2c_snake_f46(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2, f32 var_p3, u32 var_p4) {
  u32 var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4;
  f32 var_f0;
  var_f0 = var_p0;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l5 = var_i0;
  var_f0 = var_p1;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l6 = var_i0;
  var_f0 = var_p2;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l7 = var_i0;
  var_f0 = var_p3;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l8 = var_i0;
  var_i0 = var_l5;
  var_i1 = var_l6;
  var_i2 = var_l7;
  var_i3 = var_l8;
  var_i4 = var_p4;
  w2c_snake_f45(instance, var_i0, var_i1, var_i2, var_i3, var_i4);
  FUNC_EPILOGUE;
}

void w2c_snake_f47(w2c_snake* instance, u32 var_p0, u32 var_p1, u32 var_p2, u32 var_p3) {
  u32 var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, var_l11 = 0, 
      var_l12 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  var_i0 = var_p0;
  var_i1 = var_p2;
  var_i0 -= var_i1;
  var_l9 = var_i0;
  var_i0 = var_p1;
  var_i1 = var_p2;
  var_i0 -= var_i1;
  var_l10 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_p2;
  var_i0 += var_i1;
  var_l11 = var_i0;
  var_i0 = var_p1;
  var_i1 = var_p2;
  var_i0 += var_i1;
  var_l12 = var_i0;
  var_i0 = var_l11;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l12;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l9;
  var_i1 = instance->w2c_g43;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l10;
  var_i1 = instance->w2c_g44;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_l9;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_l9 = var_i0;
  }
  var_i0 = var_l10;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_l10 = var_i0;
  }
  var_i0 = var_l11;
  var_i1 = instance->w2c_g43;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    var_i0 = instance->w2c_g43;
    var_i1 = 1u;
    var_i0 -= var_i1;
    var_l11 = var_i0;
  }
  var_i0 = var_l12;
  var_i1 = instance->w2c_g44;
  var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
  if (var_i0) {
    var_i0 = instance->w2c_g44;
    var_i1 = 1u;
    var_i0 -= var_i1;
    var_l12 = var_i0;
  }
  var_i0 = var_l10;
  var_l6 = var_i0;
  var_L8: 
    var_i0 = var_l9;
    var_l5 = var_i0;
    var_i0 = instance->w2c_memoryRegionCanvasBytesOffset;
    var_i1 = instance->w2c_g44;
    var_i2 = var_l6;
    var_i1 -= var_i2;
    var_i2 = instance->w2c_g43;
    var_i1 *= var_i2;
    var_i2 = var_l5;
    var_i1 += var_i2;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_l4 = var_i0;
    var_L9: 
      var_i0 = var_l5;
      var_i1 = var_p0;
      var_i0 -= var_i1;
      var_l7 = var_i0;
      var_i0 = var_l6;
      var_i1 = var_p1;
      var_i0 -= var_i1;
      var_l8 = var_i0;
      var_i0 = var_l7;
      var_i1 = var_l7;
      var_i0 *= var_i1;
      var_i1 = var_l8;
      var_i2 = var_l8;
      var_i1 *= var_i2;
      var_i0 += var_i1;
      var_i1 = var_p2;
      var_i2 = var_p2;
      var_i1 *= var_i2;
      var_i0 = (u32)((s32)var_i0 <= (s32)var_i1);
      if (var_i0) {
        var_i0 = var_l4;
        var_i1 = var_p3;
        i32_store(&instance->w2c_memory, (u64)(var_i0), var_i1);
      }
      var_i0 = var_l4;
      var_i1 = 4u;
      var_i0 += var_i1;
      var_l4 = var_i0;
      var_i0 = var_l5;
      var_i1 = 1u;
      var_i0 += var_i1;
      var_l5 = var_i0;
      var_i0 = var_l5;
      var_i1 = var_l11;
      var_i0 = var_i0 != var_i1;
      if (var_i0) {goto var_L9;}
    var_i0 = var_l6;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l6 = var_i0;
    var_i0 = var_l6;
    var_i1 = var_l12;
    var_i0 = var_i0 != var_i1;
    if (var_i0) {goto var_L8;}
  var_Bfunc:;
  FUNC_EPILOGUE;
}

void w2c_snake_f48(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2, u32 var_p3) {
  u32 var_l4 = 0, var_l5 = 0, var_l6 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  f32 var_f0;
  var_f0 = var_p0;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l4 = var_i0;
  var_f0 = var_p1;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l5 = var_i0;
  var_f0 = var_p2;
  var_i0 = I32_TRUNC_S_F32(var_f0);
  var_l6 = var_i0;
  var_i0 = var_l4;
  var_i1 = var_l5;
  var_i2 = var_l6;
  var_i3 = var_p3;
  w2c_snake_f47(instance, var_i0, var_i1, var_i2, var_i3);
  FUNC_EPILOGUE;
}

void w2c_snake_f49(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4;
  var_i0 = 0u;
  var_i1 = 0u;
  var_i2 = instance->w2c_g43;
  var_i3 = instance->w2c_g44;
  var_i4 = instance->w2c_g41;
  w2c_snake_f45(instance, var_i0, var_i1, var_i2, var_i3, var_i4);
  FUNC_EPILOGUE;
}

void w2c_snake_f50(w2c_snake* instance, f32 var_p0, f32 var_p1, f32 var_p2, u32 var_p3) {
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0;
  var_f0 = var_p0;
  instance->w2c_g65 = var_f0;
  var_f0 = var_p1;
  instance->w2c_g66 = var_f0;
  var_f0 = var_p2;
  instance->w2c_g67 = var_f0;
  var_i0 = var_p3;
  instance->w2c_g68 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f51(w2c_snake* instance, u64 var_p0) {
  f32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i3;
  u64 var_j0;
  f32 var_f0, var_f1, var_f2;
  var_f0 = instance->w2c_g67;
  var_f1 = 8;
  var_f0 /= var_f1;
  var_l1 = var_f0;
  var_j0 = var_p0;
  var_f1 = var_l1;
  var_f2 = 2;
  var_i3 = instance->w2c_g41;
  w2c_snake_f52(instance, var_j0, var_f1, var_f2, var_i3);
  var_j0 = var_p0;
  var_f1 = var_l1;
  var_f2 = 1;
  var_i3 = instance->w2c_g68;
  w2c_snake_f52(instance, var_j0, var_f1, var_f2, var_i3);
  var_f0 = instance->w2c_g65;
  var_f1 = var_l1;
  var_f2 = 8;
  var_f1 *= var_f2;
  var_f0 += var_f1;
  instance->w2c_g65 = var_f0;
  FUNC_EPILOGUE;
}

void w2c_snake_f52(w2c_snake* instance, u64 var_p0, f32 var_p1, f32 var_p2, u32 var_p3) {
  f32 var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i4;
  u64 var_j0, var_j1;
  f32 var_f0, var_f1, var_f2, var_f3;
  var_f0 = var_p1;
  var_f1 = var_p2;
  var_f0 *= var_f1;
  var_l4 = var_f0;
  var_f0 = var_p1;
  var_f1 = var_l4;
  var_f0 -= var_f1;
  var_f1 = 0.5;
  var_f0 *= var_f1;
  var_l5 = var_f0;
  var_f0 = 0;
  var_l6 = var_f0;
  var_f0 = 0;
  var_l7 = var_f0;
  var_L0: 
    var_j0 = var_p0;
    var_j1 = 1ull;
    var_j0 &= var_j1;
    var_i0 = (u32)(var_j0);
    if (var_i0) {
      var_f0 = instance->w2c_g65;
      var_f1 = var_l7;
      var_f2 = var_p1;
      var_f1 *= var_f2;
      var_f2 = var_l5;
      var_f1 += var_f2;
      var_f0 += var_f1;
      var_f1 = instance->w2c_g66;
      var_f2 = var_l6;
      var_f3 = var_p1;
      var_f2 *= var_f3;
      var_f3 = var_l5;
      var_f2 += var_f3;
      var_f1 += var_f2;
      var_f2 = var_l4;
      var_f3 = var_l4;
      var_i4 = var_p3;
      w2c_snake_f46(instance, var_f0, var_f1, var_f2, var_f3, var_i4);
    }
    var_j0 = var_p0;
    var_j1 = 1ull;
    var_j0 >>= (var_j1 & 63);
    var_p0 = var_j0;
    var_f0 = var_l7;
    var_f1 = 6.5;
    var_i0 = var_f0 < var_f1;
    if (var_i0) {
      var_f0 = var_l7;
      var_f1 = 1;
      var_f0 += var_f1;
      var_l7 = var_f0;
    } else {
      var_f0 = var_l6;
      var_f1 = 1;
      var_f0 += var_f1;
      var_l6 = var_f0;
      var_f0 = 0;
      var_l7 = var_f0;
    }
    var_f0 = var_l6;
    var_f1 = 7.5;
    var_i0 = var_f0 < var_f1;
    if (var_i0) {goto var_L0;}
  FUNC_EPILOGUE;
}

void w2c_snake_f53(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  u64 var_j0;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g112;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 1u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g113;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 2u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g114;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 3u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g115;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 4u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g116;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 5u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g117;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 6u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g118;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 7u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g119;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 8u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g120;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = 9u;
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = instance->w2c_g121;
    w2c_snake_f51(instance, var_j0);
    goto var_Bfunc;
  }
  var_Bfunc:;
  FUNC_EPILOGUE;
}

void w2c_snake_f54(w2c_snake* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g143;
  var_i1 = instance->w2c_memoryRegionLogBytesOffset;
  var_i0 += var_i1;
  var_i1 = var_p0;
  i32_store8(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = instance->w2c_g143;
  var_i1 = 1u;
  var_i0 += var_i1;
  instance->w2c_g143 = var_i0;
  FUNC_EPILOGUE;
}

void w2c_snake_f55(w2c_snake* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  var_i0 = 1u;
  var_l1 = var_i0;
  var_L0: 
    var_i0 = var_l1;
    var_i1 = 10u;
    var_i0 *= var_i1;
    var_l1 = var_i0;
    var_i0 = var_p0;
    var_i1 = var_l1;
    var_i0 = I32_DIV_S(var_i0, var_i1);
    var_i1 = 9u;
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
    if (var_i0) {goto var_L0;}
  var_L1: 
    var_i0 = var_p0;
    var_i1 = var_l1;
    var_i0 = I32_DIV_S(var_i0, var_i1);
    var_l2 = var_i0;
    var_i0 = var_l2;
    var_i1 = instance->w2c_g70;
    var_i0 += var_i1;
    w2c_snake_f54(instance, var_i0);
    var_i0 = var_p0;
    var_i1 = var_l2;
    var_i2 = var_l1;
    var_i1 *= var_i2;
    var_i0 -= var_i1;
    var_p0 = var_i0;
    var_i0 = var_l1;
    var_i1 = 10u;
    var_i0 = I32_DIV_S(var_i0, var_i1);
    var_l1 = var_i0;
    var_i0 = var_l1;
    var_i1 = 0u;
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
    if (var_i0) {goto var_L1;}
  FUNC_EPILOGUE;
}

void w2c_snake_f56(w2c_snake* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = instance->w2c_g143;
  w2c_imports_logFromNBytesOfMemory(instance->w2c_imports_instance, var_i0);
  var_i0 = 0u;
  instance->w2c_g143 = var_i0;
  FUNC_EPILOGUE;
}

f32 w2c_snake_f57(w2c_snake* instance, f32 var_p0, f32 var_p1) {
  f32 var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0;
  f32 var_f0, var_f1, var_f2;
  var_f0 = var_p0;
  var_f1 = var_p0;
  var_f2 = var_p1;
  var_f1 /= var_f2;
  var_f1 = wasm_floorf(var_f1);
  var_f2 = var_p1;
  var_f1 *= var_f2;
  var_f0 -= var_f1;
  var_l2 = var_f0;
  var_f0 = var_l2;
  var_f1 = 0;
  var_i0 = var_f0 < var_f1;
  if (var_i0) {
    var_f0 = var_p1;
    var_f1 = var_l2;
    var_f0 -= var_f1;
    goto var_Bfunc;
  }
  var_f0 = var_l2;
  goto var_Bfunc;
  var_Bfunc:;
  FUNC_EPILOGUE;
  return var_f0;
}
